version: '3.8'
services:
  web:
    image: hsd
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LikeAndSubscribe1!"
    ports:
      - "1433:1433"
    volumes:
      - "D:/DockerVolumes/SqlData/data:/var/opt/mssql/data"
      - "D:/DockerVolumes/SqlData/secrets:/var/opt/mssql/secrets"
    container_name: mssql-server
    restart: unless-stopped

